### PR TITLE
Port to grmtools 0.6.

### PR DESCRIPTION
**Pull request by ltratt**
Use this opportunity to move to the simple `Span` interface rather than the slightly clunky `Lexeme<StorageT>` idiom.

### CODE REVIEW

**Comment by ltratt** [comment]
This needs two things before merging:

1) https://github.com/softdevteam/grmtools/pull/157 needs merging
2) I need to publish a 0.6 release to crates.io.

However, I thought it might help you see what the new API looks like before we make a 0.6 release. Comments welcome!

**Comment by ptersilie** [comment]
https://github.com/softdevteam/grmtools/pull/157 is merging. Let me know when you've done updated the crate. And I'll merge this too.

**Comment by ltratt** [comment]
This should work. Let's check first!

bors try

**Comment by ltratt** [comment]
OK, so as and when you're ready, this can be merged.

**Pull request merged**
