### PR TITLE
Prepare a 0.2.0 release.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by vext01** [comment]
This PR is fine, but I went to look at `CHANGES.md` to see what caused the bump and saw this:
image

I'm guessing that's `"\""` which markdown has interpreted? I guess you want to escape the backslash?

You probably want to fix that before doing the release?

**Comment by ltratt** [comment]
Oops -- good spot! I think that https://github.com/softdevteam/snare/pull/48/commits/526a5e074161b8315ed7ca6b9c4adb4c1c629a15 fixes the problem.

**Comment by vext01** [comment]
image

If you are happy, please squash. I thought you might have wrapped it in backticks too, but that's pedantry of the highest order :P

**Comment by ltratt** [comment]
You're right -- fixed in https://github.com/softdevteam/snare/pull/48/commits/259b98893437071a8c27280278a10ded6836d59f.

**Comment by vext01** [comment]
You are going to love this :)

image

**Comment by ltratt** [comment]
Already fixed in https://github.com/softdevteam/snare/pull/48/commits/28ee4c51fd18cac4b8548b5a5aa5cd58dd99de72!

**Comment by vext01** [comment]
image

LGTM, please squash.

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
