### PR TITLE
Split apart binding to a port from running the HTTP server.

### PR DESCRIPTION
**Pull request by ltratt**
This paves the way for us to, in the future, change the UID of snare from root to a non-root user.

### CODE REVIEW

**Comment by vext01** [comment]
Can't we just bind to a port > 1024? Then we wouldn't need to be root.

**Comment by ltratt** [comment]
> Can't we just bind to a port > 1024? Then we wouldn't need to be root.

People might want to bind to such a port -- I think we should support that (at some point).

**Comment by vext01** [comment]
> People might want to bind to such a port

Personally, I'd run the program unprivileged and use a firewall rule.

Either way, code looks good. Shall I merge?

**Comment by ltratt** [comment]
Yes please.

**Pull request merged**
