### PR TITLE
Add more logging to syslog

### PR DESCRIPTION
**Pull request by ltratt**
The main commit here is https://github.com/softdevteam/snare/commit/0879778ede6a566bb2cca5ea8e1893df27af53ef.

### CODE REVIEW

**Comment by ltratt** [comment]
Don't ask me how I forgot the code in https://github.com/softdevteam/snare/pull/27/commits/ca45c9785fd18b546222b1253e815178127d43ec, but I did. That will need squashing.

**Comment by vext01** [comment]
Looks good. One comment.

**Comment by vext01** [comment]
Please squash.

**Comment by ltratt** [comment]
Squashed.

**Comment by ltratt** [comment]
@vext01 Maybe try bors again?

**Comment by vext01** [comment]
Ugh, another crash...

bors r+

**Pull request merged**
