### PR TITLE
Migrate to github merge queues.

### PR DESCRIPTION
**Pull request by vext01**

### CODE REVIEW

**Comment by vext01** [comment]
Failed off the bat :P Investigating.

**Comment by vext01** [comment]
Investigating how to re-run the check. Hoping we don't have to close and re-open. That would be annoying for (e.g.) transient errors.

**Comment by ltratt** [comment]
> Instead I logged in to the buildbot web ui and clicked "rebuild".

That seems to have updated the status check, so that's actually not *so* bad.

**Comment by vext01** [comment]
> That seems to have updated the status check

Yes, I needed that, or the PR would never be deemed ready.

**Comment by vext01** [comment]
There we go!

**Pull request merged**
