### PR TITLE
Remove the pointlessly paranoid "always check the queue every minute".

### PR DESCRIPTION
**Pull request by ltratt**
This paranoia was entirely pointless, because if it was ever necessary, we would simply get stuck elsewhere. The idea was that, perhaps, sometimes we might not be notified that there's a job on the queue so we should (infrequently) check the queue even if we haven't been told there's an update. However, this could only happen if poll() failed. If that happened, then our ability to read stderr/stdout from child processes would also fail, at which point we'd be stuffed. But poll() isn't very likely to fail, so the paranoia is completely
pointless: we might  as well simplify the code and be done with it!

### CODE REVIEW

**Comment by vext01** [comment]
Maybe I don't understand, but if you can't miss a notification, why don't you pass `INFTIM` as the timeout?

**Comment by ltratt** [comment]
> Maybe I don't understand, but if you can't miss a notification, why don't you pass INFTIM as the timeout?

Sometimes we're also waiting on processes to finally terminate. That's not something that `poll` can tell us about, so we have to wake up every so often and explicitly check. [`kqueue` can check for this, but it's not portable :(]

**Comment by vext01** [comment]
> Sometimes we're also waiting on processes to finally terminate.

I see. Would the signal mask argument of `ppoll()` help (to catch `SIGCHILD`)?

**Comment by vext01** [comment]
If I understand correctly, a signal-based approach would be better, as at the moment you will only check for dead processes once every 16 minutes.

**Comment by ltratt** [comment]
> If I understand correctly, a signal-based approach would be better, as at the moment you will only check for dead processes once every 16 minutes.

No, we check every second.

I'm not sure wheterh `ppoll` and a mask works. I need to look into it, but I think that would be for a future PR.

**Comment by vext01** [comment]
> No, we check every second.

I must be missing something. You wait up to either `TIMEOUT * 1000` or `RECHECK_TIMEOUT * 1000` where the constants are 1 and 5 seconds respectively (according to the comment next to them).

**Comment by vext01** [comment]
I see the confusion. poll takes milliseconds.

So you wait either 1 second, 5 seconds or `INFTIM` (-1), depending on some stuff.

I don't really understand the code, so if that's intentional, let's move on?

**Comment by ltratt** [comment]
Now that I think about it, I think I can simplify this even further. Bear with me...

**Comment by ltratt** [comment]
Take a gander at https://github.com/softdevteam/snare/pull/11/commits/205df41e23b3f78353d35620dbe4155576f01436

**Comment by vext01** [comment]
LGTM, please squash.

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
